#!/bin/bash
##SBATCH -J lu1
#SBATCH -o blockLuRuntime       # output and error file name (%j expands to jobID)
#SBATCH -n 1              # total number of mpi tasks requested
#SBATCH -p gpu     # queue (partition) -- normal, development, etc.
#SBATCH -t 20:00:00        # run time (hh:mm:ss) - 20 seconds
#SBATCH -A EE-382C-EE361C-Multi
#SBATCH --mail-user=donghui@utexas.edu # replace by your email
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
./blockludecomp.out 10000 1
./blockludecomp.out 10000 10
./blockludecomp.out 10000 50
./blockludecomp.out 10000 100
./blockludecomp.out 10000 200
./blockludecomp.out 10000 500
./blockludecomp.out 10000 1000
./blockludecomp.out 10000 2000
